# fly.toml app configuration file generated for carbon-bear-xrpl on 2023-07-11T13:06:03+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "carbon-bear-xrpl"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "bash ./scripts/migrate.sh"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8081
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "60s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/resources/healthcheck"
    protocol = "http"
